### ISSUE TITLE
How to set log direction in SCDF

### ISSUE THREAD

**Issue by duyetphamm** [spring-cloud/spring-cloud-dataflow#3635]
How can I configure the log folder of SCDF and their tasks
I have tried 2 way:
_ The 1st way is changing LOG_FILE in logback-spring.xml:
```
<property name="LOG_FILE" 
			  value="D:/logs/test" />
```
_ The 2nd way is set application.properties
`spring.cloud.deployer.local.workingDirectoriesRoot=D:\\Deploy`

However, These cases do not works, the log of task when I launched is written on java.io.tmpdir (C:/..../temp/).

**Comment by sabbyanandan** [comment]
HI, @duyetphamm. We have had an issue around this, and that has been resolved via https://github.com/spring-cloud/spring-cloud-deployer-local/commit/aac68f50816f3a194a75e34e96eae549140aafd3. The fix should be included in the latest 2.3 RC1 release - please upgrade and let us know if you see issues with it.

**Comment by duyetphamm** [comment]
Hi @sabbyanandan, I have used spring-cloud-dataflow-server-core version 2.2.2.RELEASE and  spring-cloud-deployer-local 2.0.6.RELEASE for my project. However, it still not work.
I had set
`spring.cloud.deployer.local.workingDirectoriesRoot=D:\\Deploy`
But the log was in C:\Users\DUYET\AppData\Local\Temp\1720502026000\JobA-92cc8a1f-a3e0-4949-9521-915e73166dbf

**Comment by sabbyanandan** [comment]
Unfortunately, we didn't backport that fix in 2.2.2 GA. It is _only_ available in 2.3 RC1 or 2.3 BUILD-SNAPSHOT. We are aiming to ship 2.3 GA by next week, so it's coming soon. Please switch to 2.3 RC1 if you are able to.

**Comment by duyetphamm** [comment]
Is version 2.3 GA uploaded Mr.@sabbyanandan ?

**Comment by duyetphamm** [comment]
can i disable spring.cloud.deployer.local.workingDirectoriesRoot? because I can set up the log by using logback

**Comment by sabbyanandan** [comment]
Hi, @duyetphamm. As I mentioned previously, the fix is only available in 2.3.x release line, so please switch to the latest 2.3 RC2 release. You may want to watch the SCDF GitHub repo, so you can get notifications on when 2.3.x GA is released. 

Lastly, we don't usually monitor closed issues, so for new questions, please use StackOverflow or Gitter.
