### ISSUE TITLE
SCDF server fails to access docker hub behind HTTP proxy

### ISSUE THREAD

**Issue by sadovnikov** [spring-cloud/spring-cloud-dataflow#4295]
**Description:**
With version 2.5.3 setting `https.proxyHost`, `https.proxyPort` and `http.nonProxyHosts` system properties was enough to let the server to talk outside. For example, it could retrieve metadata of docker images in Docker Hub.

We are testing 2.7.0 now and this is not enough anymore. `ApplicationConfigurationMetadataResolver` catches `Connection timed out` exception on opening of `/dashboard/#/apps/source/<app name>`. This would not be a big problem, but with `2.5.3` the misconfigured proxy was causing failures to deploy Streams, which using applications with docker images from Docker hub.

**Release versions:**

Installed in Kubernetes using Bitnami Helm chart

```
$ curl 'http://localhost:8080/about' -i -X GET -H 'Accept: application/json'
HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 21 Dec 2020 15:57:34 GMT

{"featureInfo":{"analyticsEnabled":true,"streamsEnabled":true,"tasksEnabled":true,"schedulesEnabled":true,"monitoringDashboardType":"NONE"},"versionInfo":{"implementation":{"name":"spring-cloud-dataflow-server","version":"2.7.0"},"core":{"name":"Spring Cloud Data Flow Core","version":"2.7.0"},"dashboard":{"name":"Spring Cloud Dataflow UI","version":"3.0.0"},"shell":{"name":"Spring Cloud Data Flow Shell","version":"2.7.0","url":"https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"}},"securityInfo":{"authenticationEnabled":false,"authenticated":false,"username":null,"roles":[]},"runtimeEnvironment":{"appDeployer":{"deployerImplementationVersion":"2.6.0","deployerName":"Spring Cloud Skipper Server","deployerSpiVersion":"2.6.0","javaVersion":"1.8.0_275","platformApiVersion":"","platformClientVersion":"","platformHostVersion":"","platformSpecificInfo":{"default":"kubernetes","data-pipelines":"kubernetes","kime":"kubernetes","data-enrichment":"kubernetes","patstat-bf":"kubernetes","search-process":"kubernetes","search-service-layer":"kubernetes","inbox":"kubernetes","aly":"kubernetes"},"platformType":"Skipper Managed","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},"taskLaunchers":[{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"search-process","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"data-enrichment","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"kime","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"kime","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"inbox","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"aly","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"data-pipelines","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"patstat-bf","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"},{"deployerImplementationVersion":"2.5.0","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.0","javaVersion":"1.8.0_275","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"search-service-layer","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.5.RELEASE","springVersion":"5.2.10.RELEASE"}]},"monitoringDashboardInfo":{"url":"","refreshInterval":15,"dashboardType":"NONE","source":"default-scdf-source"},"_links":{"self":{"href":"http://localhost:8080/about"}}}
```

**Additional context:**

The relatively new `ContainerRegistryAutoConfiguration` uses `HttpClients.custom()`, not `HttpClients.createSystem()`. Could this be the reason? https://github.com/spring-cloud/spring-cloud-dataflow/blob/8644a5cdef59e5fba6456c200ef626575820862b/spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryAutoConfiguration.java#L187

Exception trace:

```
2020-12-21 15:03:33.713  WARN 1 --- [nio-8080-exec-3] ApplicationConfigurationMetadataResolver : Failed to retrieve properties for resource Docker Resource [docker:springcloudstream/file-source-kafka:2.1.2.RELEASE] because of ConnectException: Connection timed out (Connection timed out)
2020-12-21 15:03:33.718 DEBUG 1 --- [nio-8080-exec-3] ApplicationConfigurationMetadataResolver : (Details) for failed to retrieve properties for resource:Docker Resource [docker:springcloudstream/file-source-kafka:2.1.2.RELEASE]

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://auth.docker.io/token": Connect to auth.docker.io:443 [auth.docker.io/52.5.11.128, auth.docker.io/52.1.121.53, auth.docker.io/107.23.149.57, auth.docker.io/18.232.227.119, auth.docker.io/54.236.131.166, auth.docker.io/3.218.162.19, auth.docker.io/52.72.232.213, auth.docker.io/52.20.56.50] failed: Connection timed out (Connection timed out); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to auth.docker.io:443 [auth.docker.io/52.5.11.128, auth.docker.io/52.1.121.53, auth.docker.io/107.23.149.57, auth.docker.io/18.232.227.119, auth.docker.io/54.236.131.166, auth.docker.io/3.218.162.19, auth.docker.io/52.72.232.213, auth.docker.io/52.20.56.50] failed: Connection timed out (Connection timed out)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:746)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:712)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:600)
	at org.springframework.cloud.dataflow.container.registry.authorization.DockerOAuth2RegistryAuthorizer.getAuthorizationHeaders(DockerOAuth2RegistryAuthorizer.java:116)
    .......................................................................................
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to auth.docker.io:443 [auth.docker.io/52.5.11.128, auth.docker.io/52.1.121.53, auth.docker.io/107.23.149.57, auth.docker.io/18.232.227.119, auth.docker.io/54.236.131.166, auth.docker.io/3.218.162.19, auth.docker.io/52.72.232.213, auth.docker.io/52.20.56.50] failed: Connection timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:87)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:109)
	at org.springframework.boot.actuate.metrics.web.client.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:81)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737)
	... 68 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 87 common frames omitted
```

**Comment by tzolov** [comment]
@sadovnikov thanks for  reporting this!

**Some context:** 
With SCDF 2.5.3 (and older) the app metadata (e.g. their properties) for the jar and docker apps was bundled in separate jars and served from a Maven repository. 
In the SCDF 2.7+ this is still true for the jar SCDF applications, but for the apps coming form container images, the metadata is bundled inside the images themself (as config labels). To access the metadata, SCDF talks with the target Container  Registry (like Docker Hub) over the Docker Registry HTTP V2 API (using the RestTemplate internally. So the `https.proxyHost`, `https.proxyPort` and `http.nonProxyHosts` properties that configure the maven client will not help. 
Instead we might have to enable/configure the RestTemplate for cache proxy configurations. 

@sadovnikov can you please elaborate what HTTP proxy are you using so we cat try to reproduce the issue and try to find a solution for it.

**Comment by Baykonur** [comment]
@tzolov , thanks for the quick return. I work with @sadovnikov and our Network Team came up with the following reply:
> They could use any HTTP proxy for trying to reproduce it, we use Blue Coat ProxySG.

**Comment by sadovnikov** [comment]
@tzolov, thanks for picking this up! The bug is indeed is not about applications, but about SCDF itself failing to reach the Container Registry. We run SCDF in Kubernetes and all applications come from docker images. They use Uri-s like `docker://springcloudstream/file-source-kafka:2.1.4.RELEASE`. 

I traced the exception and found that `DockerOAuth2RegistryAuthorizer` uses Rest Template, which does not seem configured to use system properties. This is why I pointed to `ContainerRegistryAutoConfiguration`, line 187.

The `ps` below shows how the server is started inside the pod container (I replaced the domain name with `aaa.bbb.ccc`). We use the same system properties with `2.5.3` and, when absent or misconfigured, they give a problem with the same symptoms. 

```
$ ps -ef | cat
UID        PID  PPID  C STIME TTY          TIME CMD
1001         1     0  0 Dec16 ?        00:02:21 java -Dhttps.proxyHost=proxylb.aaa.bbb.ccc -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=localhost|*.aaa.bbb.ccc|172.*|*.svc|*.cluster.local|10.14.* -jar -Duser.home=/ /opt/bitnami/spring-cloud-dataflow/spring-cloud-dataflow.jar --spring.config.additional-location=/opt/bitnami/spring-cloud-dataflow/conf/application.yml
1001        63     0  0 Dec16 pts/0    00:00:00 sh
1001       856     0  0 08:31 pts/1    00:00:00 sh
1001       865   856  0 08:32 pts/1    00:00:00 ps -ef
1001       866   856  0 08:32 pts/1    00:00:00 [cat] 
```

Possibly helpful and somewhat related to this: trying to resolve this problem ourselves, we tried adding `HTTPS_PROXY` and `NO_PROXY` environment variables. Their presence influences the behaviour of `fabric8` Kubernetes client used by SCDF server, but nothing else. Hence we removed them.

**Comment by tzolov** [comment]
Thank you @sadovnikov and @Baykonur, 
Based on your description i've put together a fix that allows configuring http proxy (host + port) for the allowing SCDF server access the container registries over proxy: https://github.com/spring-cloud/spring-cloud-dataflow/pull/4296

This is a preliminary work (in case you want to test it) and i need to test with with a real http proxy configuration, before we can merge it. 
Also the PR assumes that the same configured http proxy will be used to access the metadata for all possible container registries. E.g. with SCDF you can register the app container images from different Container registries.  So if the http proxy is enabled it will apply for all those different registries. 

Does this make sense to you? Or do you think we should allow separate http proxy configuration per different container registry?

**Comment by sadovnikov** [comment]
It's very normal to have a single Proxy configuration for the entire process. I've never come across an organisation (yet), which uses multiple proxies ;) If requests to a registry should not go through a proxy, `nonProxyHosts` are used. There should be a way to bypass proxy for certain hosts or registries. 

Therefore, I wonder if there are any benefits of configuring the proxy through application properties instead of the system properties. The [HttpClientBuilder](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/index.html?org/apache/http/impl/client/SystemDefaultHttpClient.html), when used with `useSystemProperties()`, takes into account a long list of properties. This can be created with [HttpClients.createSystem()](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/index.html?org/apache/http/impl/client/HttpClients.html)

**Comment by sadovnikov** [comment]
I'd like to test the version from #4296 (and my own fix for this issue), however, the build instructions in https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/appendix-building.adoc are not complete. There are Maven dependencies on SNAPSHOTS of other projects ;( What needs to be built in order to get those dependencies in local Maven repo?

**Comment by jvalkeal** [comment]
There's 10 different projects/repos which are part of dataflow build "train" and all those are on snapshots. When you do `./mvnw clean package -DskipTests` it should work just fine.

**Comment by tzolov** [comment]
@sadovnikov, I see how using the `HttpClientBuilder`'s native properties might look convenient, but, IMO, it violates the proper design principles. 
We should not couple SCDF with a particular proprietary library and its properties. What would happen if we decide to sue `RestTemplate` (RT) with different connection factory or given that the `RT` is in maintenance mode, what would happen after we upgrade it to `WebClient`. So we can not expose internal libraries properties as SCDF configuration properties. Especially static properties.

**Comment by sadovnikov** [comment]
@jvalkeal, unfortunately the "train" is indeed very long. `./mvnw clean package -DskipTests` immideately fails to resolve `org.springframework.cloud:spring-cloud-dataflow-build:pom:2.8.0-SNAPSHOT`. After building `spring-cloud-dataflow-build` it fails on `org.springframework.cloud:spring-cloud-dataflow-common-dependencies:pom:2.8.0-SNAPSHOT` and `org.springframework.cloud:spring-cloud-skipper-dependencies:pom:2.7.0-SNAPSHOT`

**Comment by sadovnikov** [comment]
@tzolov finally I was able to test the snapshot with `docker.io/sadovnikov/spring-cloud-dataflow:2.8.0-debian-10-r0` image, which is 
```
FROM docker.io/bitnami/spring-cloud-dataflow:2.7.0-debian-10-r0
COPY spring-cloud-dataflow.jar /opt/bitnami/spring-cloud-dataflow/spring-cloud-dataflow.jar
```

Without adding `spring.cloud.dataflow.container.httpProxy.host` and `spring.cloud.dataflow.container.httpProxy.port` the behaviour does not change, which is good and expected :thumbsup:

We register applications from public and private docker registries. For example, `docker://springcloudstream/file-source-kafka:2.1.2.RELEASE` and `docker://containerhub.aaa.bbb.ccc:6666/enrichment-feeder-processor-docker:1.0.0-a726545c`. After adding new settings I was able to see details of the application from `docker.io` :thumbsup:. I was expecting a problem with opening details of the application from the internal registry (it's not accessible via proxy). However, the (missing) details were showed with NPE in the logs

```
2021-01-07 11:36:36.349  WARN 1 --- [nio-8080-exec-5] ApplicationConfigurationMetadataResolver : Failed to retrieve properties for resource Docker Resource [docker:containerhub.aaa.bbb.ccc:6666/enrichment-feeder-processor-docker:1.0.0-a726545c] because of NullPointerException:
2021-01-07 11:36:36.350 DEBUG 1 --- [nio-8080-exec-5] ApplicationConfigurationMetadataResolver : (Details) for failed to retrieve properties for resource:Docker Resource [docker:containerhub.aaa.bbb.ccc:6666/enrichment-feeder-processor-docker:1.0.0-a726545c]

java.lang.NullPointerException: null
	at org.springframework.cloud.dataflow.container.registry.ContainerRegistryService.getRegistryRequest(ContainerRegistryService.java:172)
	at org.springframework.cloud.dataflow.configuration.metadata.container.DefaultContainerImageMetadataResolver.getImageLabels(DefaultContainerImageMetadataResolver.java:53)
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.resolvePropertiesFromContainerImage(BootApplicationConfigurationMetadataResolver.java:215)
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:163)
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.getInfo(AppRegistryController.java:191)
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.info(AppRegistryController.java:165)
```

I believe it's thrown due to missing `spring.cloud.dataflow.container.registry-configurations`. 
* There is some information about configuring registries on https://dataflow.spring.io/docs/feature-guides/general/application-metadata/#using-metadata-container-image-labels, but it does not help me to configure them. Could you help me to configure it? or point to documentation?
* We cannot predict all registries, which will be used by the projects, and NPEs will be thrown. Seems https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryService.java#L169 returns `null` and then `.getAuthorizationType()` is being called on it. Can a default config be used here?

I'd like to test that applications from both public and private registries can be registered (and displayed) and deployed too (deployments with missing proxy configurations were failing in `2.5.3`)

**Comment by tzolov** [comment]
@sadovnikov , thank you for the testing  and feedback!

* I will look into the `NPE`.  Missing registry conf can be logged but should not lead to NPE. 

* Regarding the the configuration of the Custom Registry. Can you elaborate about your SCDF configuration? I assume it k8s and you are using yaml? Is it kubectl, bitnami or .. ? 
In general here is the `default` dockerhub registry configuration build-in in the SCDF: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml#L74-L80  As you can see it is called `default`. You can add more registry configurations under the `registry-configurations` tag. 
```
spring:
  cloud:
    dataflow:
      container:
        registry-configurations:
          <YOUR-Customer-RegName>:
            registry-host: ...
            authorization-type: ...
```
The [Use Metadata Image Labels](https://dataflow.spring.io/docs/feature-guides/general/application-metadata/#using-metadata-container-image-labels) doc and this [javadoc](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryConfiguration.java#L24-L57
) provides some hints (not in yaml) about how you can configure different type of registries.
And finally if you use a  [Private Docker Registry](https://dataflow.spring.io/docs/installation/kubernetes/helm/#private-docker-registry), then you do NOT have to configure it explicitly but just mount the secretes as shown [here](https://dataflow.spring.io/docs/installation/kubernetes/helm/#volume-mounted-secretes) and the necessary configuration will be generated for you.   

* Regarding 
> I'd like to test that applications from both public and private registries can be registered (and displayed) and deployed too without exceptions 
I assume that you mean that we should have the proxy configuration per-registry. E.g. you may have registries that use the proxy and other that doesn't?

**Comment by sadovnikov** [comment]
@tzolov  with the configuration below I managed to pass the point of NPE

```
  container:
    httpProxy:
      host: proxylb.aaa.bbb.ccc
      port: 8080
    registry-configurations:
      dockerhub-mirror:
        authorization-type: anonymous
        registry-host: containerhub.aaa.bbb.ccc:8888
      private-prod:
        authorization-type: anonymous
        registry-host: containerhub.aaa.bbb.ccc:6666
      private-snapshots:
        authorization-type: anonymous
        registry-host: containerhub.aaa.bbb.ccc:7777
```

However, now it throws JSON parsing error:

```
org.springframework.web.client.RestClientException: Error while extracting response for type [class java.lang.String] and content type [application/vnd.docker.container.image.v1+json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:120)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1034)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1017)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:750)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:620)
	at org.springframework.cloud.dataflow.container.registry.ContainerRegistryService.getImageBlob(ContainerRegistryService.java:229)
```

The request it tries to send is `https://containerhub.aaa.bbb.ccc:6666/v2/enrichment-feeder-processor-docker/blobs/sha256:3e8d2c02a33d4226ebc008d22a42148718acd98a023d17472a4ecde0795a386d`. If I curl it myself, I get a correct JSON response. I believe `ContainerRegistryService` uses the configured proxy. We need to have `noProxyHosts`

**Comment by sadovnikov** [comment]
We install SCDF with Bitnami chart, although we had to fork it and modify a bit to add support for multiple "platforms"

> I assume that you mean that we should have the proxy configuration per-registry. E.g. you may have registries that use the proxy and other that doesn't?

If adding something like `noProxyHosts` is not possible, having proxy configuration per registry is an option. Although, if the proxy is configured, it will be configured the same way for all public registries.

**Comment by tzolov** [comment]
* @sadovnikov i've just updated the PR to handle the NPE in case of missing registry configurations. Apparently we handle this (in the 2.6.x branch) but missed it for the 2.7.

* Is the JSON parsing error handled gracefully, e.g. it is logged but has not other side effects? or it cripples throughout the calls stack? Perhaps you can share more from the log. 

* Ok, i understand that we need to support simultaneously access to both proxy and non-proxy hosts. I need somme time to think how to do it with less changes. The problem is that we have to pre-create and manage 2 rest-templates  (only configured with proxy and another without) and as we already have to rest-templates (for ssl and ssl-less access) that means we will end up with 4 templates instances. I need some time to see if there is a better way to handle this. Will have some solution by Monday.

**Comment by sadovnikov** [comment]
* great, thank you! I will build another snapshot on Monday

* the JSON parsing error is seen only because I enabled DEBUG logging for `org.springframework.cloud.dataflow.configuration` logger. Otherwise, it would just log 

```
WARN 1 --- [nio-8080-exec-7] ApplicationConfigurationMetadataResolver : Failed to retrieve properties for resource Docker Resource.... because of MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]
```

* Thanks again for handling this problem!

**Comment by sadovnikov** [comment]
I need to investigate more the JSON parsing error: after removal of the proxy configuration it still exists

**Comment by tzolov** [comment]
@sadovnikov i've just updated the PR to allow enable/disable http-proxy per each Registry configuration.  Use the new `useHttpProxy` property to enable proxy for particular configurations. It is disabled by default.
For example `spring.cloud.dataflow.container.registry-configurations[your-registry-cofn-name].use-http-proxyr=true`.
Please let me know if this solves your requirements.

**Comment by sadovnikov** [comment]
@tzolov with the snapshot version from the PR we do get metadata (labels, etc) of the images from Docker Hub and we do get responses from our private registries. The configuration below is used

```
spring:
  cloud:
    dataflow:   
      container:
        httpProxy:
          host: proxylb.aaa.bbb.ccc
          port: 8080
        registry-configurations:
          default:
            authorization-type: dockeroauth2
            extra:
              registryAuthUri: https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell
            registry-host: registry-1.docker.io
            use-http-proxy: true
          dockerhub-mirror:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:8888
          private-prod:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:6666
          private-snapshots:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:7777
```

It's ok to merge the PR and to close this ticket. 

Although does not seem related to "proxies", we still get `com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of 'java.lang.String' out of START_OBJECT token` exception from `ContainerRegistryService#getImageBlob()` method, when it queries our private registries. 

Bodies of the responses from both Docker Hub and private registries contain JSON of the same format. However, the response from Docker Hub comes with `Content-Type: application/octet-stream`, while private repositories (Nexus) respond with `Content-Type: application/vnd.docker.container.image.v1+json`. Apparently, this is the reason for the exception which does not break anything.  Still, should [octetToStringMessageConverter](https://github.com/tzolov/spring-cloud-dataflow/blob/gh-4295-container-metadata-proxy-support/spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerImageRestTemplateFactory.java#L143) hangle more media types?

**Comment by tzolov** [comment]
@sadovnikov thank you for you elaboration! I'm glad that the proxy functionally is working!
Regarding the JSON issue, i've just updated the PR to allow support application+json content as well. 
Would greatly appreciate if you can test it ageist your repos.

**Comment by tzolov** [comment]
@sadovnikov, just noticed in your configuration. You don't need the following section because it is already defined in the SCDF confs:
```yaml
          default:
            authorization-type: dockeroauth2
            extra:
              registryAuthUri: https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell
            registry-host: registry-1.docker.io
```

You only need to add only the fields you want to override or the new such(e.g. use-http-proxy). I believe the this configuration should be identical:
```yaml
pring:
  cloud:
    dataflow:   
      container:
        httpProxy:
          host: proxylb.aaa.bbb.ccc
          port: 8080
        registry-configurations:
          default:
            use-http-proxy: true
          dockerhub-mirror:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:8888
          private-prod:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:6666
          private-snapshots:
            authorization-type: anonymous
            registry-host: containerhub.aaa.bbb.ccc:7777
```

**Comment by sadovnikov** [comment]
@tzolov Great! I was not sure if the presence of "default" in our config with override the default "default" or will merge the two ;) I'll build another snapshot and will give it a try asap

**Comment by sadovnikov** [comment]
@tzolov the simplified configuration of `default` still works 👍 . 

However, the problem with parsing of JSON response is still there. I added some logging to `ContainerRegistryService`.  In https://gist.github.com/sadovnikov/8e5683411883f4fe5ce1ba4ea28798ab#file-gistfile1-txt you can find the unmodified logs and the result of `curl -v` of the same URL. For comparison, the response from Docker Hub is https://gist.github.com/sadovnikov/8e5683411883f4fe5ce1ba4ea28798ab#file-docker-hub-response-log

**Comment by tzolov** [comment]
@sadovnikov , please hold on. I think i found something related to the issue and will update the PR shortly

**Comment by tzolov** [comment]
@sadovnikov , i've fixed the PR. Hopefully this will solve the json handling issue. 

(P.S. if you want to add metadata to your custom apps, you can find some related docs here: https://dataflow.spring.io/docs/feature-guides/general/application-metadata/#configure-app-starter-metadata-maven-plugin )

**Comment by sadovnikov** [comment]
@tzolov with the latest code the exception is gone :tada: 

We'll try adding metadata to our custom apps later. However, I believe your PR #4296 (when the build succeeds) can be merged. Thank you very much for your support too

**Comment by CEDDM** [comment]
Hi,
Thanks for your work !
In my company, the proxy needs authentication. Maybe you coud add 2 other properties to handle it 
Something like `spring.cloud.dataflow.container.httpProxy.user` and `spring.cloud.dataflow.container.httpProxy.password`
Would be great !

**Comment by sadovnikov** [comment]
@CEDDM, is using `http://username:password@proxy.thing.com:8080/` format of the proxy URL an option for you? The password would be in the open form anyway

**Comment by tzolov** [comment]
Hi @CEDDM, 
Is the @sadovnikov suggestion working for you?

**Comment by CEDDM** [comment]
Hi @sadovnikov and sorry for the late answer
We have sometimes troubles with this kind of URL format because our username is our email address (so with an @) breaking the string.
Sometimes encoding the @ with %40 works, but not all the time ...
