### ISSUE TITLE
Exceptions while running 2.11.5 version with docker compose

### ISSUE THREAD

**Issue by sumantrana** [spring-cloud/spring-cloud-dataflow#6031]
**Description:**
Multiple exceptions being raised while running SCDF with docker compose.

1. Grafana container dies: During the launch, there is a certificate error and grafana container dies without any detailed information.   It only prints out 2 lines in the log:
```
grafana                     | Error: ✗ Get "https://grafana.com/api/plugins/repo/digrich-bubblechart-panel": x509: certificate signed by unknown authority
prometheus-rsocket-proxy    | Spring Cloud Bindings Enabled
grafana exited with code 1
```

2. There is an exception raised from the prometheus rsocket proxy. This keeps on repeating at 10 sec intervals:
```
prometheus-rsocket-proxy    | 2024-10-28T22:59:09.370Z ERROR 1 --- [or-http-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [867cda53-1]  500 Server Error for HTTP GET "/metrics/proxy"
prometheus-rsocket-proxy    |
prometheus-rsocket-proxy    | java.lang.ClassCastException: class io.prometheus.metrics.model.snapshots.SummarySnapshot$SummaryDataPointSnapshot cannot be cast to class io.prometheus.metrics.model.snapshots.HistogramSnapshot$HistogramDataPointSnapshot (io.prometheus.metrics.model.snapshots.SummarySnapshot$SummaryDataPointSnapshot and io.prometheus.metrics.model.snapshots.HistogramSnapshot$HistogramDataPointSnapshot are in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @2f92e0f4)
prometheus-rsocket-proxy    | 	at io.prometheus.metrics.expositionformats.PrometheusTextFormatWriter.writeHistogram(PrometheusTextFormatWriter.java:138) ~[prometheus-metrics-exposition-formats-1.2.1.jar:na]
prometheus-rsocket-proxy    | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
prometheus-rsocket-proxy    | Error has been observed at the following site(s):
prometheus-rsocket-proxy    | 	*__checkpoint ? HTTP GET "/metrics/proxy" [ExceptionHandlingWebHandler]
prometheus-rsocket-proxy    | Original Stack Trace:
prometheus-rsocket-proxy    | 		at io.prometheus.metrics.expositionformats.PrometheusTextFormatWriter.writeHistogram(PrometheusTextFormatWriter.java:138) ~[prometheus-metrics-exposition-formats-1.2.1.jar:na]
prometheus-rsocket-proxy    | 		at io.prometheus.metrics.expositionformats.PrometheusTextFormatWriter.write(PrometheusTextFormatWriter.java:68) ~[prometheus-metrics-exposition-formats-1.2.1.jar:na]
prometheus-rsocket-proxy    | 		at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:167) ~[micrometer-registry-prometheus-1.13.1.jar:1.13.1]
prometheus-rsocket-proxy    | 		at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:163) ~[micrometer-registry-prometheus-1.13.1.jar:1.13.1]
prometheus-rsocket-proxy    | 		at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:136) ~[micrometer-registry-prometheus-1.13.1.jar:1.13.1]
prometheus-rsocket-proxy    | 		at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:123) ~[micrometer-registry-prometheus-1.13.1.jar:1.13.1]
prometheus-rsocket-proxy    | 		at io.micrometer.prometheus.rsocket.PrometheusController.proxyMetrics(PrometheusController.java:156) ~[prometheus-rsocket-proxy-server-2.0.0-M1.jar:2.0.0-M1]
prometheus-rsocket-proxy    | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
prometheus-rsocket-proxy    | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
prometheus-rsocket-proxy    | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
prometheus-rsocket-proxy    | 		at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
prometheus-rsocket-proxy    | 		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:198) ~[spring-webflux-6.1.10.jar:6.1.10]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:153) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:63) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:241) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:121) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:259) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:865) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:339) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.6.7.jar:3.6.7]
prometheus-rsocket-proxy    | 		at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:1176) ~[reactor-netty-http-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:715) ~[reactor-netty-core-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:481) ~[reactor-netty-core-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:781) ~[reactor-netty-http-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:259) ~[reactor-netty-http-1.1.20.jar:1.1.20]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
prometheus-rsocket-proxy    | 		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
prometheus-rsocket-proxy 
```

3. There is an exception from the dataflow server during initialisation:

```
dataflow-server             | 2024-10-28 22:59:27.158  INFO 1 --- [nio-9393-exec-4] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
dataflow-server             | 2024-10-28 22:59:28.364 ERROR 1 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
dataflow-server             |
dataflow-server             | java.lang.RuntimeException: Error reading from URL [https://dataflow.spring.io/task-maven-3-0-x]
dataflow-server             | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.resourceAsLines(DefaultAppRegistryService.java:451)
dataflow-server             | 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
dataflow-server             | 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
dataflow-server             | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
dataflow-server             | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
dataflow-server             | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
dataflow-server             | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
dataflow-server             | 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
dataflow-server             | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.importAll(DefaultAppRegistryService.java:373)
dataflow-server             | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService$$FastClassBySpringCGLIB$$a8bae4.invoke(<generated>)
dataflow-server             | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
dataflow-server             | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
dataflow-server             | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
dataflow-server             | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
dataflow-server             | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
dataflow-server             | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
dataflow-server             | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
dataflow-server             | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server             | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
dataflow-server             | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
dataflow-server             | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService$$EnhancerBySpringCGLIB$$586538e2.importAll(<generated>)
dataflow-server             | 	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.registerAll(AppRegistryController.java:441)
dataflow-server             | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server             | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
dataflow-server             | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dataflow-server             | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dataflow-server             | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
dataflow-server             | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
dataflow-server             | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
dataflow-server             | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
dataflow-server             | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
dataflow-server             | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
dataflow-server             | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
dataflow-server             | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
dataflow-server             | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
dataflow-server             | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
dataflow-server             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
dataflow-server             | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
dataflow-server             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
dataflow-server             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
dataflow-server             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
dataflow-server             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
dataflow-server             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
dataflow-server             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server             | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
dataflow-server             | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
dataflow-server             | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
dataflow-server             | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
dataflow-server             | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
dataflow-server             | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
dataflow-server             | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
dataflow-server             | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
dataflow-server             | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
dataflow-server             | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
dataflow-server             | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
dataflow-server             | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
dataflow-server             | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
dataflow-server             | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
dataflow-server             | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
dataflow-server             | 	at java.base/java.lang.Thread.run(Unknown Source)
dataflow-server             | Caused by: java.io.FileNotFoundException: https://dataflow.spring.io/task-maven-3-0-x
dataflow-server             | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
dataflow-server             | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
dataflow-server             | 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
dataflow-server             | 	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:187)
dataflow-server             | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.resourceAsLines(DefaultAppRegistryService.java:447)
dataflow-server             | 	... 78 common frames omitted
dataflow-server             |
dataflow-app-import-task    | Maven Task apps imported
```

**Release versions:**
```json
{
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": false,
    "monitoringDashboardType": "NONE"
  },
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.11.5"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.11.5"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.4.6"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.11.5",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.11.5/spring-cloud-dataflow-shell-2.11.5.jar"
    }
  },
  "securityInfo": {
    "authenticationEnabled": false,
    "authenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.11.5",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.11.5",
      "javaVersion": "11.0.19",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "local"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.18",
      "springVersion": "5.3.39"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "unknown",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "unknown",
        "javaVersion": "11.0.19",
        "platformApiVersion": "Linux 6.5.11-linuxkit",
        "platformClientVersion": "6.5.11-linuxkit",
        "platformHostVersion": "6.5.11-linuxkit",
        "platformSpecificInfo": {},
        "platformType": "Local",
        "springBootVersion": "2.7.18",
        "springVersion": "5.3.39"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "refreshInterval": 15,
    "dashboardType": "NONE",
    "source": "default-scdf-source"
  },
  "gitAndBuildInfo": {
    "git": {
      "branch": "main",
      "commit": {
        "id": "edc71ff",
        "time": "2024-09-12T13:11:37Z"
      }
    },
    "build": {
      "artifact": "spring-cloud-dataflow-server",
      "name": "Spring Cloud Data Flow Server",
      "time": "2024-09-13T10:05:45.364Z",
      "version": "2.11.5",
      "group": "org.springframework.cloud"
    }
  },
  "_links": {
    "self": {
      "href": "http://localhost:9393/about"
    }
  }
}
```

**Custom apps:**

**Steps to reproduce:**
Download the yml files from `https://github.com/spring-cloud/spring-cloud-dataflow/tree/main/src/docker-compose`, set the dataflow and skipper versions to 2.11.5 and ruin the following command:
```
docker compose -f docker-compose.yml -f docker-compose-kafka.yml -f docker-compose-prometheus.yml up
```
java version is set to: `sdk use java 17.0.10-tem`

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

**Additional context:**

**Comment by cppwfs** [comment]
For item `3`it appears that the redirect for retrieving tasks is not working.  We are looking into it.

**Comment by corneil** [comment]
I used the following:
```shell
export DATAFLOW_VERSION=2.11.5
./src/docker-compose/dc.sh rabbitmq mariadb prometheus up
```
This resulted in errors trying to find k8s.
Then I added `- SPRING_CLOUD_KUBERNETES_ENABLED=false` to `dataflow-server.environment` in `docker-compose.yml` and also `skipper-server.environment`.

Then I noticed grafana won't come up reporting bad request on the grafana/plugins.
I removed `ENV GF_INSTALL_PLUGINS digrich-bubblechart-panel,savantly-heatmap-panel,grafana-piechart-panel,jdbranham-diagram-panel` from `src/grafana/prometheus/docker/grafana/Dockerfile` and executed `./src/deploy/images/build-grafana-image.sh`


```shell
./src/docker-compose/dc.sh rabbitmq mariadb prometheus rm
./src/docker-compose/dc.sh rabbitmq mariadb prometheus up
```
I launched `timestamp` task and check Grafana Dashboard.

Then I noticed grafana reporting authentication errors. I'm assuming it can't authenticate with prometheus.

**Comment by cppwfs** [comment]
Issue `3` has been resolved.   You should be able to register the Default Task Apps now.

**Comment by sumantrana** [comment]
Hi, just wanted to check if all 3 issues have been resolved or only the 3rd one. Because as per @corneil Grafana is still not working. 
Also what is the update on Issue# 2

**Comment by bhcha** [comment]
hi, @corneil , @cppwfs 
I still have Issue#2 not resolved
I received the files from the URL below and tried to run them, but it failed.

https://github.com/spring-cloud/spring-cloud-dataflow/tree/main/src/docker-compose

**Comment by cppwfs** [comment]
@bhcha Can you create a new issue for what you are facing.    Please provide the versions used and stack traces.   Thank you !
